# STATUS: ALIVE
# LAST-AUDIT: 2026-05-11
# FEEDS: thesis paper.tex §A.7 (appendix: hour-classification metrics)
# CLAIM: Builds an appendix LaTeX table with the 24-hour classification metrics
# used to define critical vs flat hours. Reads from
# /tmp/hour_classification_metrics.csv (generated by an inline duckdb query).

from __future__ import annotations
from pathlib import Path
import pandas as pd

REPO = Path(__file__).resolve().parents[3]
SRC = REPO  # placeholder
CSV = Path("/tmp/hour_classification_metrics.csv")
OUT = REPO / "thesis" / "paper" / "tables" / "tab_hour_classification.tex"

CRITICAL = {5, 6, 7, 8, 16, 17, 18, 19, 20, 21, 22}
FLAT = {1, 2, 3}


def cls(h):
    if h in CRITICAL: return "critical"
    if h in FLAT: return "flat"
    return "dropped"


def main():
    df = pd.read_csv(CSV)
    df["class"] = df["hour"].apply(cls)
    df = df.sort_values("hour")
    tex = []
    tex.append(r"\begin{tabular}{r r r r r r l}")
    tex.append(r"\toprule")
    tex.append(r"$h$ & load (GW) & solar (GW) & net-load (GW) & $\sigma_{\text{within}}$ (MW) & $\Delta$load (MW) & class \\")
    tex.append(r"\midrule")
    for _, r in df.iterrows():
        h = int(r["hour"])
        emph = r"\textbf{" if r["class"] == "critical" else (r"\textit{" if r["class"] == "flat" else "{")
        end = "}"
        line = (f"{emph}{h:>2}{end} & {r['load_gw']:.1f} & {r['solar_gw']:.1f} & "
                f"{r['netload_gw']:.1f} & {r['sigma_netload_mw']:.0f} & "
                f"{r['delta_load_mw']:+.0f} & \\textit{{{r['class']}}} \\\\")
        tex.append(line)
    tex.append(r"\bottomrule")
    tex.append(r"\end{tabular}")
    OUT.write_text("\n".join(tex))
    print(f"wrote: {OUT}")


if __name__ == "__main__":
    main()
