*! F5 per-unit Allaz-Vila regression with HDFE absorption
*! Auto-generated by f5_per_unit_reghdfe.py
clear all
set more off
use "/Users/pabloparamio/Desktop/CEMFI/2nd Year/Master Thesis/mtu15_project/results/regressions/f5_per_unit_panel.dta", clear

label define regime_lbl 1 "pre-IDA" 2 "3-sess" 3 "ISP15-win" 4 "DA60/ID15" 5 "DA15/ID15"
label values regime regime_lbl

di as txt _newline "=== F5 per-unit Allaz-Vila with reghdfe (HDFE: unit + year-month + hour-of-day + DOW) ==="

* Spec 1: sparse FE — unit FE + year-month FE only, slope by regime
di as txt _newline "--- Spec 1: sparse (unit + year-month FE) ---"
reghdfe dq_ida_mwh c.q_da_mw_hour##i.regime, ///
    absorb(unit_id year_month) ///
    cluster(date_num) ///
    nocons

* Spec 2: augmented exogenous — add hour-of-day FE + DOW FE + VRE control
di as txt _newline "--- Spec 2: augmented (unit + year-month + hour + DOW FE + VRE) ---"
reghdfe dq_ida_mwh c.q_da_mw_hour##i.regime vre_gwh, ///
    absorb(unit_id year_month hour_of_day dow) ///
    cluster(date_num) ///
    nocons

* Save the augmented spec results to CSV via outreg2 alternative: estout
matrix b = e(b)
matrix V = e(V)
local cn : colnames b
di as txt _newline "Coefficient names:" `"`cn'"'

* Compute per-regime slope: β_pre + β_interaction_r
preserve
clear
local regimes pre_IDA three_sess ISP15_win DA60_ID15 DA15_ID15
set obs 5

gen regime_str = ""
gen beta = .
gen se = .

local i = 1
foreach r of local regimes {
    local stata_r : word `i' of "1.regime" "2.regime" "3.regime" "4.regime" "5.regime"
    replace regime_str = "`r'" in `i'
    if `i' == 1 {
        replace beta = _b[c.q_da_mw_hour] in `i'
        replace se   = _se[c.q_da_mw_hour] in `i'
    }
    else {
        lincom c.q_da_mw_hour + `i'.regime#c.q_da_mw_hour
        replace beta = r(estimate) in `i'
        replace se   = r(se) in `i'
    }
    local i = `i' + 1
}
gen t = beta / se
gen p = 2 * normal(-abs(t))
list, clean noobs
export delimited "/Users/pabloparamio/Desktop/CEMFI/2nd Year/Master Thesis/mtu15_project/results/regressions/f5_per_unit_reghdfe.csv", replace
restore

* Joint Wald: are interactions jointly different from zero?
di as txt _newline "--- Joint Wald: H0 all regime × q_DA interactions = 0 ---"
test 2.regime#c.q_da_mw_hour 3.regime#c.q_da_mw_hour ///
     4.regime#c.q_da_mw_hour 5.regime#c.q_da_mw_hour
